# Generated by Django 6.0 on 2026-01-12 12:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('poster_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('backdrop_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cast_member',
                'indexes': [models.Index(fields=['name'], name='cast_member_name_bfe0a2_idx'), models.Index(fields=['birth_date'], name='cast_member_birth_d_fbe62d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='episode_details', serialize=False, to='api.content')),
                ('episode_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='movie_details', serialize=False, to='api.content')),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('box_office_revenue', models.BigIntegerField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tv_show_details', serialize=False, to='api.content')),
                ('total_seasons', models.IntegerField(default=1)),
                ('total_episodes', models.IntegerField(default=1)),
                ('status', models.CharField(default='ongoing', max_length=20)),
            ],
            options={
                'db_table': 'tv_show',
            },
        ),
        migrations.CreateModel(
            name='ContentCast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_type', models.CharField(default='actor', max_length=50)),
                ('billing_order', models.IntegerField(blank=True, null=True)),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.castmember')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.content')),
            ],
            options={
                'db_table': 'content_cast',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('smart_tv', 'Smart TV'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=20)),
                ('device_name', models.CharField(max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'genre',
                'indexes': [models.Index(fields=['name'], name='genre_name_bff4c4_idx'), models.Index(fields=['display_order'], name='genre_display_86e92d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.content')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
            ],
            options={
                'db_table': 'content_genre',
            },
        ),
        migrations.CreateModel(
            name='MaturityLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_age', models.IntegerField()),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'maturity_level',
                'indexes': [models.Index(fields=['code'], name='maturity_le_code_cc8b0f_idx'), models.Index(fields=['minimum_age'], name='maturity_le_minimum_1c3906_idx'), models.Index(fields=['display_order'], name='maturity_le_display_1f4b08_idx')],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='maturity_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.maturitylevel'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('language_code', models.CharField(default='en', max_length=2)),
                ('is_kid_profile', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_quality', models.CharField(choices=[('SD', 'Standard Definition'), ('HD', 'High Definition'), ('FHD', 'Full HD'), ('UHD', 'Ultra HD')], max_length=10)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('download_path', models.CharField(blank=True, max_length=500, null=True)),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api.content')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api.device')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='api.profile')),
            ],
            options={
                'db_table': 'download',
            },
        ),
        migrations.CreateModel(
            name='DeviceLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_country', models.CharField(blank=True, max_length=2, null=True)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='api.device')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logins', to='api.profile')),
            ],
            options={
                'db_table': 'device_login',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.profile')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('contains_spoilers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.profile')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_concurrent_streams', models.IntegerField(default=1)),
                ('max_profiles', models.IntegerField(default=1)),
                ('supports_uhd', models.BooleanField(default=False)),
                ('supports_hdr', models.BooleanField(default=False)),
                ('supports_dolby_atmos', models.BooleanField(default=False)),
                ('allows_downloads', models.BooleanField(default=False)),
                ('max_download_devices', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plan',
                'indexes': [models.Index(fields=['name'], name='subscriptio_name_fa4370_idx'), models.Index(fields=['price_monthly'], name='subscriptio_price_m_ba69c9_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_c95204_idx'), models.Index(fields=['display_order'], name='subscriptio_display_4e6528_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('billing_cycle_start', models.DateTimeField()),
                ('billing_cycle_end', models.DateTimeField()),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('payment_gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subscriptionplan')),
            ],
            options={
                'db_table': 'billing_history',
                'ordering': ['-billing_cycle_start'],
            },
        ),
        migrations.CreateModel(
            name='UserContentInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_watch_time_seconds', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('is_in_watchlist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='api.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to='api.profile')),
            ],
            options={
                'db_table': 'user_content_interaction',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('payment_method_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_method_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_started_at', models.DateTimeField()),
                ('watch_ended_at', models.DateTimeField(blank=True, null=True)),
                ('watched_seconds', models.IntegerField(default=0)),
                ('start_position_seconds', models.IntegerField(blank=True, null=True)),
                ('end_position_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='api.content')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.device')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='api.profile')),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watch_started_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_time_seconds', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='api.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='api.profile')),
            ],
            options={
                'db_table': 'watch_progress',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country_code'], name='user_country_048a41_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_855a50_idx'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.season'),
        ),
        migrations.AddField(
            model_name='season',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.tvshow'),
        ),
        migrations.AddIndex(
            model_name='contentcast',
            index=models.Index(fields=['content'], name='content_cas_content_c0c771_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcast',
            index=models.Index(fields=['cast_member'], name='content_cas_cast_me_ac85be_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcast',
            index=models.Index(fields=['billing_order'], name='content_cas_billing_d97c0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentcast',
            unique_together={('content', 'cast_member', 'role_type')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user'], name='device_user_id_a3d3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='device_device__4f75d1_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'last_login_at'], name='device_user_id_9ca0d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_name')},
        ),
        migrations.AddIndex(
            model_name='contentgenre',
            index=models.Index(fields=['content'], name='content_gen_content_c05719_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenre',
            index=models.Index(fields=['genre'], name='content_gen_genre_i_216b1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentgenre',
            unique_together={('content', 'genre')},
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['release_date'], name='content_release_177e55_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='content_content_bc205e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['maturity_level'], name='content_maturit_029074_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['release_date', 'content_type'], name='content_release_1273d6_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_deleted', 'release_date'], name='content_is_dele_0fd9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profile_user_id_2c597b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_kid_profile'], name='profile_is_kid__0bae94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['profile'], name='download_profile_2f13b0_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['device'], name='download_device__588e52_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['profile', 'downloaded_at'], name='download_profile_d828f9_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['expires_at', 'download_status'], name='download_expires_e8f293_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelogin',
            index=models.Index(fields=['device'], name='device_logi_device__14f8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelogin',
            index=models.Index(fields=['profile'], name='device_logi_profile_13c9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelogin',
            index=models.Index(fields=['device', 'login_at'], name='device_logi_device__c3813d_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelogin',
            index=models.Index(fields=['profile', 'login_at'], name='device_logi_profile_774c01_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content'], name='rating_content_9fd950_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content', 'rating_value'], name='rating_content_925121_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('profile', 'content')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['profile'], name='review_profile_8e4c72_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content'], name='review_content_cad15a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content', 'created_at'], name='review_content_17c287_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['profile', 'created_at'], name='review_profile_22fd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='billinghistory',
            index=models.Index(fields=['user', 'billing_cycle_start'], name='billing_his_user_id_1e3819_idx'),
        ),
        migrations.AddIndex(
            model_name='billinghistory',
            index=models.Index(fields=['invoice_number'], name='billing_his_invoice_684aad_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentinteraction',
            index=models.Index(fields=['profile'], name='user_conten_profile_70aa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentinteraction',
            index=models.Index(fields=['content'], name='user_conten_content_47eb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentinteraction',
            index=models.Index(fields=['profile', 'updated_at'], name='user_conten_profile_9462b0_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentinteraction',
            index=models.Index(fields=['content', 'total_watch_time_seconds'], name='user_conten_content_ba5f1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontentinteraction',
            unique_together={('profile', 'content')},
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user'], name='user_subscr_user_id_43eb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status'], name='user_subscr_status_2fc1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['current_period_end'], name='user_subscr_current_fdcda5_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='user_subscr_status_65db8c_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['profile'], name='watch_histo_profile_3b81ee_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['content'], name='watch_histo_content_abdee8_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['watch_started_at'], name='watch_histo_watch_s_de3e74_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['profile', 'watch_started_at'], name='watch_histo_profile_d8f939_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['content', 'watch_started_at'], name='watch_histo_content_0e216d_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['profile', 'content', 'watch_started_at'], name='watch_histo_profile_a82ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['profile', 'content'], name='ux_watch_progress'),
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('profile', 'content')},
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season'], name='episode_season__37d347_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['episode_number'], name='episode_episode_65ae15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['tv_show'], name='season_tv_show_42bd60_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['season_number'], name='season_season__51da66_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['release_date'], name='season_release_871930_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('tv_show', 'season_number')},
        ),
    ]
