# Generated by Django 6.0 on 2026-01-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='watch_histo_profile_3b81ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='watch_histo_content_abdee8_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='watch_histo_watch_s_de3e74_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='watch_histo_profile_d8f939_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='watch_histo_content_0e216d_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='watch_histo_profile_a82ed7_idx',
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['profile', '-watch_started_at'], name='watch_histo_profile_b7ca0b_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['content', '-watch_started_at'], name='watch_histo_content_16e663_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['profile', 'content', '-watch_started_at'], name='watch_histo_profile_c80d16_idx'),
        ),
    ]
