# Generated by Django 6.0 on 2026-01-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='razorpay_plan_id',
        ),
    ]
