# Generated by Django 6.0 on 2026-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='user_subscr_stripe__512dcf_idx'),
        ),
    ]
