# Generated by Django 6.0 on 2026-01-14 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_billinghistory_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stripe_event',
                'indexes': [models.Index(fields=['event_id'], name='stripe_even_event_i_1aa168_idx'), models.Index(fields=['processed_at'], name='stripe_even_process_a4eac6_idx')],
            },
        ),
    ]
