# Generated by Django 6.0 on 2026-01-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subscriptionplan_trial_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
